import {
  createContext,
  useCallback,
  useContext,
  useEffect,
  useMemo,
  useState,
  type ReactNode,
} from "react";

export type LanguageCode =
  | "de"
  | "en"
  | "fr"
  | "es"
  | "it"
  | "pt"
  | "tr"
  | "ru"
  | "hi"
  | "ar"
  | "zh"
  | "ja";

type LanguageOption = { code: LanguageCode; label: string };

/** BCP 47 tag for `Intl` formatters (dates, times) from dashboard language. */
export function localeTagForLanguage(code: LanguageCode): string {
  const map: Record<LanguageCode, string> = {
    de: "de-DE",
    en: "en-GB",
    fr: "fr-FR",
    es: "es-ES",
    it: "it-IT",
    pt: "pt-PT",
    tr: "tr-TR",
    ru: "ru-RU",
    hi: "hi-IN",
    ar: "ar-SA",
    zh: "zh-CN",
    ja: "ja-JP",
  };
  return map[code];
}

const STORAGE_KEY = "dema-app-language";
const APP_SETTINGS_KEY = "dema-app-settings";

const LANGUAGE_OPTIONS: LanguageOption[] = [
  { code: "de", label: "Deutsch" },
  { code: "en", label: "English" },
  { code: "fr", label: "Français" },
  { code: "es", label: "Español" },
  { code: "it", label: "Italiano" },
  { code: "pt", label: "Português" },
  { code: "tr", label: "Türkçe" },
  { code: "ru", label: "Русский" },
  { code: "hi", label: "हिन्दी" },
  { code: "ar", label: "العربية" },
  { code: "zh", label: "中文" },
  { code: "ja", label: "日本語" },
];

const MESSAGES: Record<LanguageCode, Record<string, string>> = {
  de: {
    navDashboard: "Dashboard",
    navSettings: "Einstellungen",
    headerSearchPlaceholder: "Suchen… Kunden-Nr., Firmenname (Vorschläge aus Datenbank)",
    headerSearchTitle: "Gespeicherte Kunden-Nr. und Firmennamen",
    headerAddNew: "Neu hinzufügen",
    headerLogout: "Abmelden",
    sidebarSales: "Sales",
    sidebarPurchase: "Purchase",
    sidebarWorkshop: "Werkstatt",
    sidebarCarWash: "Waschanlage",
    sidebarHRM: "HRM",
    navB2bPortal: "B2B Portal",
    commonCustomers: "Kunden",
    commonInventory: "Bestand",
    commonOffers: "Angebote",
    commonInquiries: "Anfragen",
    commonInvoices: "Rechnungen",
    commonReports: "Auswertungen",
    commonCalendar: "Kalender",
    commonUser: "Benutzer",
    sidebarSoldInventory: "Verkaufter Bestand",
    sidebarPickupOrders: "Abholaufträge",
    sidebarPlateSearch: "Kennzeichen Suchen",
    sidebarCreditNotes: "Gutschriften",
    sidebarPickupDeliveryCalendar: "Kalender: Abholung & Lieferung",
    sidebarWash: "Waschen",
    sidebarOrders: "Aufträge",
    sidebarCashDesk: "Kasse",
    sidebarWorkshopCore: "Werkstatt · Kernarbeit",
    sidebarWorkshopStock: "Werkstatt · Lager & Kataloge",
    sidebarWorkshopBilling: "Werkstatt · Rechnungen & Kasse",
    sidebarWorkshopMore: "Werkstatt · Planung & mehr",
    sidebarArticleIntake: "Artikeleingang",
    sidebarArticleCatalog: "Artikelkatalog",
    sidebarServiceCatalog: "Leistungskatalog",
    sidebarThirdPartyCatalog: "Fremdleistungskatalog",
    sidebarInvoicesOpen: "Offene Rechnungen",
    sidebarInvoicesPaid: "Bezahlte Rechnungen",
    sidebarAccounting: "Buchhaltung",
    sidebarSuppliers: "Lieferanten",
    sidebarEmployees: "Mitarbeiter",
    sidebarAttendance: "Anwesenheit",
    sidebarSalary: "Gehalt",
    sidebarRolesPermissions: "Rollen & Rechte",
    sidebarOnGroundTeam: "On-Ground-Team",
    onGroundTeamTitle: "Außendienst & Team vor Ort",
    onGroundKpiActive: "Vor Ort aktiv",
    onGroundKpiTransit: "Unterwegs",
    onGroundKpiStandby: "Bereitschaft",
    onGroundKpiShifts: "Schichten heute",
    onGroundRosterTitle: "Team im Einsatz",
    onGroundRoleDriver: "Fahrer",
    onGroundRoleCoordinator: "Koordinatorin",
    onGroundRoleTech: "Techniker",
    onGroundStatusOnSite: "Vor Ort",
    onGroundStatusTransit: "Fahrt",
    onGroundStatusStandby: "Bereitschaft",
    ogtStatusActive: "Aktiv",
    ogtStatusInProgress: "In Arbeit",
    ogtStatusDone: "Erledigt",
    ogtStatusPending: "Ausstehend",
    ogtStatusBreak: "Pause",
    ogtStatusOffline: "Offline",
    ogtSectionChecklists: "Checklisten",
    ogtChecklistTruck: "Checkliste Abholung LKW",
    ogtChecklistTrailer: "Checkliste Anhänger / Auflieger",
    ogtChecklistTruckDigital: "Digitale LKW-Abholcheckliste",
    ogtChecklistTrailerDigital: "Digitale Anhänger-/Auflieger-Checkliste",
    ogtFieldBrand: "Marke",
    ogtFieldType: "Typ",
    ogtFieldBody: "Aufbau",
    ogtFieldChassisNo: "Fahrgestellnr.",
    ogtFieldPnr: "P-Nr.",
    ogtChecklistCheckpoint: "Prüfpunkt",
    ogtCheckOk: "Ok",
    ogtCheckNo: "Nein",
    ogtChecklistRemarks: "Bemerkungen",
    ogtTyresAxle1: "Reifen % 1.Achse",
    ogtTyresAxle2: "2.Achse",
    ogtTyresAxle3: "3.Achse",
    ogtTyresAxle4: "4.Achse",
    ogtSignature: "Unterschrift",
    ogtEta: "ETA",
    ogtPriorityLow: "Niedrig",
    ogtSectionTeam: "Team",
    ogtSectionFahrer: "Fahrer",
    ogtSectionTasks: "Aufgaben",
    ogtSectionSchedule: "Einsatzplan",
    ogtSectionReports: "Auswertungen",
    ogtTitle: "On Ground Team",
    ogtSubtitle: "Einsatzübersicht, Teamstatus und Aufgabenplanung für das Außendienstteam.",
    ogtActiveAgents: "Aktive Agenten",
    ogtOnBreak: "Pause",
    ogtOffline: "Offline",
    ogtCoverage: "Einsatzgebiet",
    ogtFahrerActive: "Fahrer aktiv",
    ogtFahrerBreak: "Pause",
    ogtFahrerOffline: "Offline",
    ogtFahrerKmToday: "Gesamt km heute",
    ogtOpenTasks: "Offene Aufgaben",
    ogtInProgress: "In Arbeit",
    ogtDoneToday: "Heute erledigt",
    ogtHighPriority: "Hohe Priorität",
    ogtShiftsToday: "Schichten heute",
    ogtOnRoute: "Unterwegs",
    ogtCompleted: "Abgeschlossen",
    ogtLive: "Live-Status",
    ogtTasksWeek: "Aufgaben diese Woche",
    ogtOnTimeRate: "Pünktlichkeit",
    ogtAvgTime: "Ø Bearbeitungszeit",
    ogtFleetKm: "Gesamt km",
    ogtTeamOverview: "Teamübersicht – heute",
    ogtThName: "Name",
    ogtThRole: "Rolle",
    ogtThStatus: "Status",
    ogtThLocation: "Standort",
    ogtThTasks: "Aufgaben",
    ogtTaskList: "Aufgabenliste – heute",
    ogtThTask: "Aufgabe",
    ogtThAgent: "Agent",
    ogtThPriority: "Priorität",
    ogtScheduleToday: "Einsatzplan – heute",
    ogtThTime: "Uhrzeit",
    ogtTasksPerAgent: "Aufgaben je Agent (Woche)",
    ogtOnTimeStats: "Pünktlichkeitsstatistik",
    ogtFleetSummary: "Flotten-Zusammenfassung",
    ogtFleetTotal: "Fahrzeuge gesamt",
    ogtFleetActive: "Im Einsatz",
    ogtFleetKmWeek: "km diese Woche",
    ogtFleetFuel: "Ø Verbrauch",
    ogtFahrerList: "Fahrerliste",
    ogtFahrerLicense: "Führerschein",
    ogtFahrerVehicle: "Fahrzeug",
    ogtFahrerPlate: "Kennzeichen",
    ogtFahrerKm: "km heute",
    ogtFahrerFuel: "Tank %",
    ogtFahrerValid: "FS gültig bis",
    ogtFahrerFleetSize: "Fahrzeuge gesamt",
    ogtFahrerAvgFuel: "Ø Tankstand",
    weekdayMon: "Montag",
    weekdayTue: "Dienstag",
    weekdayWed: "Mittwoch",
    weekdayThu: "Donnerstag",
    weekdayFri: "Freitag",
    commonPrint: "Drucken",
    commonDate: "Datum",
    commonSales: "Verkauf",
    signatureDraw: "Zeichnen",
    signatureType: "Tippen",
    signatureClear: "Löschen",
    signatureTypePlaceholder: "Vollständigen Namen eingeben",
    settingsTitle: "Einstellungen",
    settingsDisplay: "Darstellung",
    settingsLanguage: "Sprache",
    settingsLanguageHelp: "Die ausgewählte Sprache wird im Dashboard angewendet.",
    settingsSystemAccount: "System & Konto",
    settingsAccount: "Konto",
    settingsNotifications: "Benachrichtigungen",
    settingsSecurity: "Sicherheit",
    settingsUpdatePassword: "Passwort aktualisieren",
    settingsNotificationRules: "Benachrichtigungsregeln",
    settingsQuietHours: "Ruhezeiten aktivieren (22:00 - 07:00)",
    settingsLanguageRegion: "Sprache & Region",
    settingsLiveActivity: "Live Aktivitaet",
    settingsNoActions: "Noch keine Aktionen",
    commonSave: "Speichern",
    commonClose: "Schliessen",
    commonApply: "Anwenden",
    commonName: "Name",
    commonEmail: "E-Mail",
    commonOn: "Ein",
    commonOff: "Aus",
    themeLight: "Hell",
    themeDark: "Dunkel",
    themeSystem: "System",
    settingsTimezone: "Zeitzone",
    settingsRoleProfile: "Rollenprofil",
    settingsRoleEmployee: "Mitarbeiter",
    settingsRoleManager: "Manager",
    settingsNotifySalesAlerts: "Sales Alerts",
    settingsNotifyHrmApprovals: "HRM Freigaben",
    settingsNotifyPayrollErrors: "Payroll Fehler",
    settingsNotifyB2bLeads: "B2B Leads",
    settingsDateFormat: "Datenformat",
    settingsActionChangePassword: "Passwort ändern",
    settingsActionManage2fa: "2FA verwalten",
    settingsActionReviewRoles: "Rollen prüfen",
    settingsActionNotificationRules: "Benachrichtigungsregeln",
    settingsActionLanguageRegion: "Sprache & Region",
    settings2faStatus: "2FA",
    settingsLastPasswordChange: "Letzte Passwortaenderung",
    settingsNever: "Noch nie",
    settingsRegion: "Region",
    settingsRegionGermany: "Deutschland",
    settingsRegionInternational: "International",
    settingsCurrentPassword: "Aktuelles Passwort",
    settingsNewPassword: "Neues Passwort",
    settingsConfirmPassword: "Passwort bestaetigen",
    settingsHint2faToggled: "2FA umgeschaltet",
    settingsHintRoleUpdated: "Rollenprofil aktualisiert",
    settingsHintFillPasswordFields: "Bitte alle Passwortfelder ausfuellen",
    settingsHintPasswordMinLength: "Neues Passwort muss mindestens 6 Zeichen haben",
    settingsHintPasswordsMismatch: "Passwoerter stimmen nicht ueberein",
    settingsHintPasswordUpdated: "Passwort erfolgreich aktualisiert",
    settingsHintNotificationRulesSaved: "Benachrichtigungsregeln gespeichert",
    settingsHintRegionSaved: "Regionseinstellungen gespeichert",
    appRedirecting: "Weiterleitung…",
    hrmTitle: "Human Resource Management",
    hrmSectionEmployees: "Mitarbeiter",
    hrmSectionAttendance: "Anwesenheit",
    hrmSectionSalary: "Gehalt",
    hrmSectionRoles: "Rollen & Rechte",
    hrmColName: "Name",
    hrmColRole: "Rolle",
    hrmColLocation: "Standort",
    hrmColStatus: "Status",
    hrmStatusActive: "Aktiv",
    hrmStatusOnboarding: "Onboarding",
    hrmLabelNewHires: "Neueinstellungen",
    hrmLabelAttrition: "Fluktuation",
    hrmLabelPresentToday: "Heute anwesend",
    hrmLabelVacation: "Urlaub",
    hrmLabelSick: "Krank",
    hrmLabelOpenShifts: "Schichten offen",
    hrmLabelStatements: "Abrechnungen",
    hrmLabelSepaStatus: "SEPA Status",
    hrmLabelValidationErrors: "Prüffehler",
    hrmLabelActiveRoles: "Aktive Rollen",
    hrmLabelMfaActive: "MFA aktiv",
    hrmLabelPrivilegedUsers: "Privilegierte User",
    hrmLabelClean: "Clean",
    dynamicAddWidget: "Widget hinzufügen",
    dynamicResetLayout: "Layout zurücksetzen",
    dynamicHint: "Ziehen Sie Widgets an eine neue Position · Ecke zum Größen ändern (nicht bei fixen Blöcken)",
    dynamicDragToMove: "Ziehen zum Verschieben",
    dynamicMoveWidget: "Widget verschieben",
    dynamicRemoveWidget: "Widget entfernen",
    welcomeTitle: "Willkommen im DEMA Management System",
    welcomeSubtitle: "Hier ist Ihre Übersicht — Sales, Purchase und Waschanlage auf einen Blick.",
    quickActionsTitle: "Schnelle Aktionen",
    quickActionCustomer: "Kunde anlegen",
    quickActionVehicle: "Fahrzeug erfassen",
    quickActionOffer: "Angebot erstellen",
    quickActionInvoice: "Rechnung erstellen",
    tasksTitle: "Aufgaben & Erinnerungen",
    tasksHigh: "Hoch",
    tasksMedium: "Mittel",
    tasksNew: "Neu",
    tasksItem1: "Angebot für Kunde Schmidt",
    tasksItem2: "Fahrzeug-Übergabe morgen 10:00",
    tasksItem3: "Rechnung #2847 prüfen",
    tasksItem4: "Waschtermin bestätigen",
    profileTime: "Zeit",
    profileStatus: "Status",
    profileActive: "Aktiv",
    profileInternalComms: "Interne Kommunikation aktiv",
    profileRoleVerified: "Rolle verifiziert",
    profileOpen: "Profil öffnen",
    salesTitle: "Verkaufsleistung",
    salesPeriod: "6 Monate",
    salesRevenue: "Umsatz",
    salesTotalRevenue: "Gesamtumsatz",
    salesClosedDeals: "Abgeschlossene Deals",
    salesProfit: "Gewinn",
    inventoryTitle: "Bestandsübersicht",
    inventoryVerfügbar: "Verfügbar",
    inventoryReserviert: "Reserviert",
    inventoryVerkauft: "Verkauft",
    financesTitle: "Finanzen diesen Monat",
    financeEinnahmen: "Einnahmen",
    financeAusgaben: "Ausgaben",
    financeGewinn: "Gewinn",
    financeIncome: "Einnahmen",
    financeExpenses: "Ausgaben",
    financeProfit: "Gewinn",
    calendarTitle: "Kalender",
    appointmentsTitle: "Heutige Termine",
    appointmentsNew: "Neuer Termin",
    widgetUnknown: "Unbekanntes Widget",
    widgetGroupTables: "Tabellen",
    widgetGroupLists: "Listen",
    widgetGroupMedia: "Medien",
    widgetGroupCharts: "Diagramme",
    widgetGroupOverviews: "Übersichten",
    widgetGroupActions: "Aktionen",
    widgetGroupPlanning: "Planung",
    widgetGroupMisc: "Sonstiges",
    widgetTitleWelcome: "Willkommen",
    widgetTitleKpi: "KPIs",
    widgetTitleTable: "Tabelle",
    widgetTitleTodoList: "To-do Liste",
    widgetTitlePicture: "Bild",
    widgetTitleGraphLine: "Linie",
    widgetTitleGraphBar: "Balken",
    widgetTitleGraphPie: "Kreis",
    widgetTitleGraphArea: "Fläche",
    widgetTitleSales: "Verkaufsleistung",
    widgetTitleInventory: "Bestandsübersicht",
    widgetTitleQuickActions: "Schnelle Aktionen",
    widgetTitleTasks: "Aufgaben & Erinnerungen",
    widgetTitleFinances: "Finanzen",
    widgetTitleUserCard: "Profil Modul",
    widgetTitleProfile: "Profil Modul",
    widgetTitleCalendar: "Kalender",
    widgetTitleAppointments: "Termine",
    widgetTitleMeetings: "Meetings",
    widgetTitleNotes: "Notizen",
    loginSecureBadge: "Sicher anmelden",
    loginTitle: "Anmelden",
    loginSubtitle:
      "Mit Ihrer geschäftlichen E-Mail ins Dashboard — oder testen Sie das Demo-Konto.",
    loginDemoTitle: "Demo-Zugang",
    loginEmail: "E-Mail",
    loginPassword: "Passwort",
    loginPlaceholderEmail: "name@firma.de",
    loginShowPassword: "Passwort anzeigen",
    loginHidePassword: "Passwort verbergen",
    loginSubmit: "Weiter zum Dashboard",
    loginNoAccount: "Noch kein Konto?",
    loginRegister: "Registrieren",
    loginB2bPortalLink: "Zum B2B-Fahrzeugportal (öffentlich)",
    signupBadge: "Neues Konto",
    signupTitle: "Konto anlegen",
    signupSubtitle: "Registrierung für das interne Dashboard (Demo: Daten nur in diesem Browser).",
    signupPasswordMismatch: "Passwörter stimmen nicht überein.",
    signupName: "Name",
    signupPassword: "Passwort",
    signupConfirmPassword: "Passwort bestätigen",
    signupPlaceholderName: "Vor- und Nachname",
    signupPlaceholderPassword: "Mindestens 6 Zeichen",
    signupPlaceholderConfirm: "Passwort wiederholen",
    signupSubmit: "Konto erstellen",
    signupHasAccount: "Bereits registriert?",
    signupLogin: "Anmelden",
    signupB2bLink: "Zum B2B-Fahrzeugportal (öffentlich)",
    customersTitle: "Kunden",
    customersNewCustomer: "Neuen Kunden erfassen",
    customersArea: "Bereich",
    deptSales: "Sales",
    deptPurchase: "Purchase",
    deptWerkstatt: "Werkstatt",
    deptWaschanlage: "Waschanlage",
    customersDeptHint:
      "Eine Maske für alle Bereiche: kunden, optional kunden_wash im Tab Waschanlage (wie beim Bearbeiten).",
    customersQuickCompanySearch: "Firmenname Schnellsuche:",
    customersSearchPlaceholder: "Suchen…",
    customersSuggestionsDb: "Vorschläge: KU-Nr. und Firmennamen aus der Datenbank",
    customersSuggestionsSaved: "Vorschläge aus gespeicherten Kunden",
    customersShow: "Zeigen",
    customersAll: "alle",
    customersMoreFilters: "Weitere Filter",
    customersLabelCustomerNr: "KundenNr.",
    customersLabelCompany: "Firmenname",
    customersLabelContact: "Ansprechpartner",
    customersLabelPhone: "Telefonnummer",
    customersLabelZip: "PLZ",
    customersLabelCity: "Ort",
    customersLabelCountry: "Land",
    customersLabelSort: "Sortierung",
    customersSortKundenNr: "Kundennummer",
    customersSortFirmenname: "Firmenname",
    customersSortOrt: "Ort",
    customersSortPLZ: "PLZ",
    customersSortTermin: "Termin",
    customersEmptyList:
      "Keine Kunden in der Liste. Filter zurücksetzen („alle“) oder neuen Kunden anlegen.",
    customersSelectionCount: "Anz. der Auswahl:",
    customersLists: "Listen",
    customersClose: "Schließen",
    customersSave: "Speichern",
    customersFileTooBig:
      "Datei zu groß (max. 2 MB in dieser Demo, bis ein Server die Dateien übernimmt).",
    customersFileReadError: "Datei konnte nicht gelesen werden.",
    customersSaveFailed: "Speichern fehlgeschlagen",
    customersThKuNr: "KU-NR",
    customersThCompany: "Firmenname",
    customersThAppointment: "Termin",
    customersThIndustry: "Branche",
    customersThStreet: "Strasse",
    customersThZip: "PLZ",
    customersThCity: "Ort",
    customersThCountry: "Land",
    customersDrawerEntity: "Kunde",
    customersLoading: "Wird geladen…",
    customersDrawerNrLabel: "KundenNr.",
    angeboteDeptHint:
      "Filter und Liste entsprechen der klassischen ANGEBOTE-Maske; Layout wie Kunden.",
    verkaufterBestandSubtitle:
      "Suche verkaufter Bestand — Filter und Spalten wie im Legacy-System.",
    verkaufterBestandCount: "Anzahl der ausgewählten Fahrzeuge:",
    abholauftraegeSubtitle: "Abholliste — Suche nach Fahrgestellnummer und Filter wie im Legacy-System.",
    abholauftraegeVinSearch: "Fahrgestellnummer suchen",
    abholauftraegeCount: "Anzahl Aufträge:",
    kennzeichenPageTitle: "Kennzeichensuche",
    kennzeichenSearchHeader: "Suche für Kennzeichen",
    kennzeichenSearchLabel: "Kennzeichen suchen:",
    kennzeichenSearchButton: "Suchen",
    kennzeichenWildcardHint:
      "Bei der Suche mit * arbeiten, um bessere Treffer zu erzielen. Beispiel: DE*MA*101",
    kennzeichenColPosition: "PositionsNr",
    kennzeichenColKz: "KZ",
    kennzeichenColTable: "Tabelle",
    kennzeichenNoHits: "Keine Treffer für diese Suche.",
    kennzeichenEnterQuery:
      "Geben Sie ein Kennzeichen ein oder nutzen Sie * als Platzhalter.",
    kennzeichenHitCount: "Treffer:",
    navDuplicateCustomers: "Doppelte Kunden",
    dupCustomersPageTitle: "Doppelte Kunden",
    dupCustomersFilterHint: "Filter wirken sofort auf die Ergebnisliste.",
    dupCustomersShow: "Zeigen",
    dupCustomersAll: "alle",
    dupCustomersKundenNr: "KundenNr:",
    dupCustomersFirma: "Firmenname:",
    dupCustomersAnsprech: "Ansprechpartner:",
    dupCustomersTel: "Telefonnummer:",
    dupCustomersFax: "Faxnummer:",
    dupCustomersBranche: "Branche:",
    dupCustomersArt: "Art:",
    dupCustomersNotKii: "nicht KII/KEG/KSL",
    dupCustomersZpk: "ZPK:",
    dupCustomersMitVerkn: "Kunde mit Verkn.",
    dupCustomersNaAnz: "Kunden NA anz.",
    dupCustomersNaHint: "Legacy-Feld; Filter folgt bei Anbindung der Daten.",
    dupCustomersAufnahmeVon: "Aufnahme von",
    dupCustomersAufnahmeBis: "Aufnahme bis",
    dupCustomersSort: "Sortierung:",
    dupCustomersSortTel: "Telefonnummer",
    dupCustomersSortBez: "Beziehung",
    dupCustomersThTel: "Telefonnummer",
    dupCustomersThT: "T",
    dupCustomersThZeichen: "Zeichen",
    dupCustomersThArt: "Art",
    dupCustomersThMarkiert: "Markiert",
    dupCustomersThBKNR: "BKNr",
    dupCustomersThBFirma: "BFirma",
    dupCustomersThBez: "Beziehung",
    dupCustomersCount: "Anz. der Ausschl:",
    dupCustomersEmptyDb:
      "Keine Dubletten ermittelt (oder noch keine passenden Kunden in der lokalen Datenbank). Nach einem leeren Start legen die Demokunden Dubletten an.",
    dupCustomersEmptyFilter: "Keine Treffer mit diesen Filtern.",
    rechnungenPageTitle: "Rechnungen",
    rechnungenQuickSearch: "Firmenname Schnellsuche:",
    rechnungenSuggestionsCompanies: "Gespeicherte Firmennamen",
    rechnungenSuggestionsKu: "Kundennummern",
    rechnungenShow: "Zeigen",
    rechnungenAll: "alle",
    rechnungenFilterHint: "Filter wirken sofort auf die Liste.",
    rechnungenNewInvoice: "Neue Rechnung erfassen",
    rechnungenLabelNr: "RechnungsNr:",
    rechnungenLabelVonRDatum: "von RDatum:",
    rechnungenLabelBisRDatum: "bis RDatum:",
    rechnungenLabelArt: "Art:",
    rechnungenLabelRechnungErst: "Rechnung erst.:",
    rechnungenLabelVerkaeufer: "Verkäufer:",
    rechnungenLabelVermerk: "Vermerk:",
    rechnungenLabelKundenNr: "KundenNr:",
    rechnungenLabelUstId: "UmsatzsteuerID:",
    rechnungenLabelPositionsNr: "PositionsNr:",
    rechnungenLabelFgst: "FahrgestellNr:",
    rechnungenLabelVerkaufsNr: "VerkaufsNr:",
    rechnungenFilterNichtErledigt: "Nicht Erledigte",
    rechnungenFilterBhCheck: "BH Check",
    rechnungenFilterNichtAbgeholt: "nicht Abgeholt",
    rechnungenSortRechnNr: "RechnungsNr",
    rechnungenSortRDatum: "R_Datum",
    rechnungenSortBetrag: "Rechnungsbetrag",
    rechnungenThRechnNr: "RechnNr",
    rechnungenThRDatum: "R_Datum",
    rechnungenThKundenNr: "KundenNr",
    rechnungenThArt: "Art",
    rechnungenThBuchung: "Buchung",
    rechnungenThBezahltAm: "Bezahltam",
    rechnungenThErsteller: "Ersteller",
    rechnungenThVerkaeufer: "Verkäufer",
    rechnungenThBetrag: "Rechnungsbetrag",
    rechnungenCount: "Anzahl Rechnungen:",
    rechnungenEmpty: "Keine Treffer. Filter mit „alle“ zurücksetzen.",
    rechnungenDrawerLabel: "Rechnung",
    rechnungenDrawerNew: "(Neu)",
    rechnungenDrawerNewHint:
      "Die vollständige Maske RECHNUNG (Positionen, Zahlungsart, Netto/Brutto, Druck) wird mit Anbindung an die API ergänzt. Hier können Sie vorerst nur die Liste filtern und bestehende Demo-Rechnungen ansehen.",
    rechnungenCloseDrawer: "Schließen",
    headerChat: "Chat",
    chatTitle: "Chat",
    chatSearchPlaceholder: "Suchen oder neuer Chat",
    chatNewChat: "Neuer Chat",
    chatNewGroup: "Neue Gruppe",
    chatEmptyList: "Noch keine Chats. Starten Sie einen neuen.",
    chatSelectThread: "Wählen Sie einen Chat aus der Liste.",
    chatBack: "Zurück",
    chatMembersCount: "{n} Mitglieder",
    chatStatusOnline: "Online",
    chatStatusOffline: "Offline",
    chatPreviewPhoto: "📷 Foto",
    chatNoMessagesYet: "Noch keine Nachrichten",
    chatMessagePlaceholder: "Nachricht",
    chatSend: "Senden",
    chatAddPhoto: "Foto",
    chatAddFile: "Datei",
    chatNoContacts: "Keine weiteren Konten. Registrieren Sie ein zweites Konto im Browser.",
    chatGroupName: "Gruppenname",
    chatGroupNamePh: "z. B. Projektteam",
    chatGroupMembers: "Mitglieder",
    chatCreateGroup: "Gruppe erstellen",
    chatGroupNeedMember: "Bitte mindestens einen Kontakt auswählen.",
    chatSendFailed: "Nachricht konnte nicht gesendet werden.",
    chatFileTooBig: "Datei zu groß (max. 2 MB in dieser Demo).",
    chatFileReadError: "Datei konnte nicht gelesen werden.",
    chatNotifBanner: "Desktop-Benachrichtigungen für neue Nachrichten aktivieren?",
    chatNotifEnable: "Aktivieren",
    chatNotifLater: "Später",
    chatNotifUnsupported: "Benachrichtigungen werden von diesem Browser nicht unterstützt.",
    chatNotifDenied: "Benachrichtigungen wurden abgelehnt.",
    chatNotifImage: "📷 Foto",
    chatNotifFile: "📎 Datei",
    chatSectionContacts: "Kontakte",
    chatSectionChats: "Chats",
    chatStatusAway: "Abwesend",
    chatYouBadge: "Sie",
    chatTickSent: "Gesendet",
    chatTickDelivered: "Zugestellt",
    chatTickRead: "Gelesen",
  },
  en: {
    navDashboard: "Dashboard",
    navSettings: "Settings",
    headerSearchPlaceholder: "Search… Customer no., company name (suggestions from database)",
    headerSearchTitle: "Saved customer numbers and company names",
    headerAddNew: "Add new",
    headerLogout: "Log out",
    sidebarSales: "Sales",
    sidebarPurchase: "Purchase",
    sidebarWorkshop: "Workshop",
    sidebarCarWash: "Car Wash",
    sidebarHRM: "HRM",
    navB2bPortal: "B2B Portal",
    commonCustomers: "Customers",
    commonInventory: "Inventory",
    commonOffers: "Offers",
    commonInquiries: "Inquiries",
    commonInvoices: "Invoices",
    commonReports: "Reports",
    commonCalendar: "Calendar",
    commonUser: "User",
    sidebarSoldInventory: "Sold Inventory",
    sidebarPickupOrders: "Pickup Orders",
    sidebarPlateSearch: "Plate Search",
    sidebarCreditNotes: "Credit Notes",
    sidebarPickupDeliveryCalendar: "Calendar: Pickup & Delivery",
    sidebarWash: "Wash",
    sidebarOrders: "Orders",
    sidebarCashDesk: "Cash Desk",
    sidebarWorkshopCore: "Workshop · Core",
    sidebarWorkshopStock: "Workshop · Stock & catalogs",
    sidebarWorkshopBilling: "Workshop · Invoicing & cash",
    sidebarWorkshopMore: "Workshop · Planning & more",
    sidebarArticleIntake: "Goods receipt",
    sidebarArticleCatalog: "Parts catalog",
    sidebarServiceCatalog: "Service catalog",
    sidebarThirdPartyCatalog: "Subcontractor services",
    sidebarInvoicesOpen: "Open invoices",
    sidebarInvoicesPaid: "Paid invoices",
    sidebarAccounting: "Accounting",
    sidebarSuppliers: "Suppliers",
    sidebarEmployees: "Employees",
    sidebarAttendance: "Attendance",
    sidebarSalary: "Salary",
    sidebarRolesPermissions: "Roles & Permissions",
    sidebarOnGroundTeam: "On Ground Team",
    onGroundTeamTitle: "Field & on-site team",
    onGroundKpiActive: "Active on site",
    onGroundKpiTransit: "In transit",
    onGroundKpiStandby: "On standby",
    onGroundKpiShifts: "Shifts today",
    onGroundRosterTitle: "Team on duty",
    onGroundRoleDriver: "Driver",
    onGroundRoleCoordinator: "Coordinator",
    onGroundRoleTech: "Technician",
    onGroundStatusOnSite: "On site",
    onGroundStatusTransit: "In transit",
    onGroundStatusStandby: "Standby",
    ogtStatusActive: "Active",
    ogtStatusInProgress: "In progress",
    ogtStatusDone: "Done",
    ogtStatusPending: "Pending",
    ogtStatusBreak: "Break",
    ogtStatusOffline: "Offline",
    ogtSectionChecklists: "Checklists",
    ogtChecklistTruck: "Truck pickup checklist",
    ogtChecklistTrailer: "Trailer / semi-trailer checklist",
    ogtChecklistTruckDigital: "Digital truck pickup checklist",
    ogtChecklistTrailerDigital: "Digital trailer / semi-trailer checklist",
    ogtFieldBrand: "Brand",
    ogtFieldType: "Type",
    ogtFieldBody: "Body",
    ogtFieldChassisNo: "Chassis no.",
    ogtFieldPnr: "P-No.",
    ogtChecklistCheckpoint: "Checkpoint",
    ogtCheckOk: "OK",
    ogtCheckNo: "No",
    ogtChecklistRemarks: "Remarks",
    ogtTyresAxle1: "Tyres % axle 1",
    ogtTyresAxle2: "Axle 2",
    ogtTyresAxle3: "Axle 3",
    ogtTyresAxle4: "Axle 4",
    ogtSignature: "Signature",
    ogtEta: "ETA",
    ogtPriorityLow: "Low",
    ogtSectionTeam: "Team",
    ogtSectionFahrer: "Drivers",
    ogtSectionTasks: "Tasks",
    ogtSectionSchedule: "Schedule",
    ogtSectionReports: "Reports",
    ogtTitle: "On Ground Team",
    ogtSubtitle: "Deployment overview, team status and task planning for the field team.",
    ogtActiveAgents: "Active Agents",
    ogtOnBreak: "On Break",
    ogtOffline: "Offline",
    ogtCoverage: "Coverage Area",
    ogtFahrerActive: "Active Drivers",
    ogtFahrerBreak: "On Break",
    ogtFahrerOffline: "Offline",
    ogtFahrerKmToday: "Total km today",
    ogtOpenTasks: "Open Tasks",
    ogtInProgress: "In Progress",
    ogtDoneToday: "Done Today",
    ogtHighPriority: "High Priority",
    ogtShiftsToday: "Shifts Today",
    ogtOnRoute: "On Route",
    ogtCompleted: "Completed",
    ogtLive: "Live Status",
    ogtTasksWeek: "Tasks this week",
    ogtOnTimeRate: "On-time rate",
    ogtAvgTime: "Avg. processing time",
    ogtFleetKm: "Total km",
    ogtTeamOverview: "Team overview – today",
    ogtThName: "Name",
    ogtThRole: "Role",
    ogtThStatus: "Status",
    ogtThLocation: "Location",
    ogtThTasks: "Tasks",
    ogtTaskList: "Task list – today",
    ogtThTask: "Task",
    ogtThAgent: "Agent",
    ogtThPriority: "Priority",
    ogtScheduleToday: "Schedule – today",
    ogtThTime: "Time",
    ogtTasksPerAgent: "Tasks per agent (week)",
    ogtOnTimeStats: "On-time statistics",
    ogtFleetSummary: "Fleet summary",
    ogtFleetTotal: "Total vehicles",
    ogtFleetActive: "In operation",
    ogtFleetKmWeek: "km this week",
    ogtFleetFuel: "Avg. consumption",
    ogtFahrerList: "Driver list",
    ogtFahrerLicense: "License",
    ogtFahrerVehicle: "Vehicle",
    ogtFahrerPlate: "Plate",
    ogtFahrerKm: "km today",
    ogtFahrerFuel: "Tank %",
    ogtFahrerValid: "License valid until",
    ogtFahrerFleetSize: "Total vehicles",
    ogtFahrerAvgFuel: "Avg. tank level",
    weekdayMon: "Monday",
    weekdayTue: "Tuesday",
    weekdayWed: "Wednesday",
    weekdayThu: "Thursday",
    weekdayFri: "Friday",
    commonPrint: "Print",
    commonDate: "Date",
    commonSales: "Sales",
    signatureDraw: "Draw",
    signatureType: "Type",
    signatureClear: "Clear",
    signatureTypePlaceholder: "Type full name",
    settingsTitle: "Settings",
    settingsDisplay: "Display",
    settingsLanguage: "Language",
    settingsLanguageHelp: "The selected language is applied across the dashboard.",
    settingsSystemAccount: "System & Account",
    settingsAccount: "Account",
    settingsNotifications: "Notifications",
    settingsSecurity: "Security",
    settingsUpdatePassword: "Update Password",
    settingsNotificationRules: "Notification Rules",
    settingsQuietHours: "Enable quiet hours (22:00 - 07:00)",
    settingsLanguageRegion: "Language & Region",
    settingsLiveActivity: "Live Activity",
    settingsNoActions: "No actions yet",
    commonSave: "Save",
    commonClose: "Close",
    commonApply: "Apply",
    commonName: "Name",
    commonEmail: "Email",
    commonOn: "On",
    commonOff: "Off",
    themeLight: "Light",
    themeDark: "Dark",
    themeSystem: "System",
    settingsTimezone: "Timezone",
    settingsRoleProfile: "Role profile",
    settingsRoleEmployee: "Employee",
    settingsRoleManager: "Manager",
    settingsNotifySalesAlerts: "Sales alerts",
    settingsNotifyHrmApprovals: "HRM approvals",
    settingsNotifyPayrollErrors: "Payroll errors",
    settingsNotifyB2bLeads: "B2B leads",
    settingsDateFormat: "Date format",
    settingsActionChangePassword: "Change password",
    settingsActionManage2fa: "Manage 2FA",
    settingsActionReviewRoles: "Review roles",
    settingsActionNotificationRules: "Notification rules",
    settingsActionLanguageRegion: "Language & region",
    settings2faStatus: "2FA",
    settingsLastPasswordChange: "Last password change",
    settingsNever: "Never",
    settingsRegion: "Region",
    settingsRegionGermany: "Germany",
    settingsRegionInternational: "International",
    settingsCurrentPassword: "Current password",
    settingsNewPassword: "New password",
    settingsConfirmPassword: "Confirm password",
    settingsHint2faToggled: "2FA toggled",
    settingsHintRoleUpdated: "Role profile updated",
    settingsHintFillPasswordFields: "Please fill all password fields",
    settingsHintPasswordMinLength: "New password must be at least 6 characters",
    settingsHintPasswordsMismatch: "Passwords do not match",
    settingsHintPasswordUpdated: "Password updated successfully",
    settingsHintNotificationRulesSaved: "Notification rules saved",
    settingsHintRegionSaved: "Region settings saved",
    appRedirecting: "Redirecting…",
    hrmTitle: "Human Resource Management",
    hrmSectionEmployees: "Employees",
    hrmSectionAttendance: "Attendance",
    hrmSectionSalary: "Salary",
    hrmSectionRoles: "Roles & Permissions",
    hrmColName: "Name",
    hrmColRole: "Role",
    hrmColLocation: "Location",
    hrmColStatus: "Status",
    hrmStatusActive: "Active",
    hrmStatusOnboarding: "Onboarding",
    hrmLabelNewHires: "New Hires",
    hrmLabelAttrition: "Attrition",
    hrmLabelPresentToday: "Present Today",
    hrmLabelVacation: "Vacation",
    hrmLabelSick: "Sick",
    hrmLabelOpenShifts: "Open Shifts",
    hrmLabelStatements: "Payroll Statements",
    hrmLabelSepaStatus: "SEPA Status",
    hrmLabelValidationErrors: "Validation Errors",
    hrmLabelActiveRoles: "Active Roles",
    hrmLabelMfaActive: "MFA Active",
    hrmLabelPrivilegedUsers: "Privileged Users",
    hrmLabelClean: "Clean",
    dynamicAddWidget: "Add widget",
    dynamicResetLayout: "Reset layout",
    dynamicHint: "Drag widgets to a new position · Use the corner to resize (except locked blocks)",
    dynamicDragToMove: "Drag to move",
    dynamicMoveWidget: "Move widget",
    dynamicRemoveWidget: "Remove widget",
    welcomeTitle: "Welcome to the DEMA Management System",
    welcomeSubtitle: "Here is your overview — Sales, Purchase, and Car Wash at a glance.",
    quickActionsTitle: "Quick Actions",
    quickActionCustomer: "Create Customer",
    quickActionVehicle: "Register Vehicle",
    quickActionOffer: "Create Offer",
    quickActionInvoice: "Create Invoice",
    tasksTitle: "Tasks & Reminders",
    tasksHigh: "High",
    tasksMedium: "Medium",
    tasksNew: "New",
    tasksItem1: "Offer for customer Schmidt",
    tasksItem2: "Vehicle handover tomorrow 10:00",
    tasksItem3: "Review invoice #2847",
    tasksItem4: "Confirm car wash appointment",
    profileTime: "Time",
    profileStatus: "Status",
    profileActive: "Active",
    profileInternalComms: "Internal communication active",
    profileRoleVerified: "Role verified",
    profileOpen: "Open Profile",
    salesTitle: "Sales Performance",
    salesPeriod: "6 Months",
    salesRevenue: "Revenue",
    salesTotalRevenue: "Total Revenue",
    salesClosedDeals: "Closed Deals",
    salesProfit: "Profit",
    inventoryTitle: "Inventory Overview",
    inventoryVerfügbar: "Available",
    inventoryReserviert: "Reserved",
    inventoryVerkauft: "Sold",
    financesTitle: "Finances This Month",
    financeEinnahmen: "Income",
    financeAusgaben: "Expenses",
    financeGewinn: "Profit",
    financeIncome: "Income",
    financeExpenses: "Expenses",
    financeProfit: "Profit",
    calendarTitle: "Calendar",
    appointmentsTitle: "Today's Appointments",
    appointmentsNew: "New Appointment",
    widgetUnknown: "Unknown widget",
    widgetGroupTables: "Tables",
    widgetGroupLists: "Lists",
    widgetGroupMedia: "Media",
    widgetGroupCharts: "Charts",
    widgetGroupOverviews: "Overviews",
    widgetGroupActions: "Actions",
    widgetGroupPlanning: "Planning",
    widgetGroupMisc: "Other",
    widgetTitleWelcome: "Welcome",
    widgetTitleKpi: "KPIs",
    widgetTitleTable: "Table",
    widgetTitleTodoList: "To-do list",
    widgetTitlePicture: "Picture",
    widgetTitleGraphLine: "Line",
    widgetTitleGraphBar: "Bar",
    widgetTitleGraphPie: "Pie",
    widgetTitleGraphArea: "Area",
    widgetTitleSales: "Sales performance",
    widgetTitleInventory: "Inventory overview",
    widgetTitleQuickActions: "Quick actions",
    widgetTitleTasks: "Tasks & reminders",
    widgetTitleFinances: "Finances",
    widgetTitleUserCard: "Profile module",
    widgetTitleProfile: "Profile module",
    widgetTitleCalendar: "Calendar",
    widgetTitleAppointments: "Appointments",
    widgetTitleMeetings: "Meetings",
    widgetTitleNotes: "Notes",
    loginSecureBadge: "Secure sign-in",
    loginTitle: "Sign in",
    loginSubtitle:
      "Use your business email to open the dashboard — or try the demo account.",
    loginDemoTitle: "Demo access",
    loginEmail: "Email",
    loginPassword: "Password",
    loginPlaceholderEmail: "name@company.com",
    loginShowPassword: "Show password",
    loginHidePassword: "Hide password",
    loginSubmit: "Continue to dashboard",
    loginNoAccount: "No account yet?",
    loginRegister: "Register",
    loginB2bPortalLink: "B2B vehicle portal (public)",
    signupBadge: "New account",
    signupTitle: "Create account",
    signupSubtitle: "Register for the internal dashboard (demo: data stays in this browser).",
    signupPasswordMismatch: "Passwords do not match.",
    signupName: "Name",
    signupPassword: "Password",
    signupConfirmPassword: "Confirm password",
    signupPlaceholderName: "First and last name",
    signupPlaceholderPassword: "At least 6 characters",
    signupPlaceholderConfirm: "Repeat password",
    signupSubmit: "Create account",
    signupHasAccount: "Already registered?",
    signupLogin: "Sign in",
    signupB2bLink: "B2B vehicle portal (public)",
    customersTitle: "Customers",
    customersNewCustomer: "Add customer",
    customersArea: "Area",
    deptSales: "Sales",
    deptPurchase: "Purchase",
    deptWerkstatt: "Workshop",
    deptWaschanlage: "Car wash",
    customersDeptHint:
      "One screen for all areas: kunden; optional kunden_wash in the Car wash tab when editing.",
    customersQuickCompanySearch: "Company quick search:",
    customersSearchPlaceholder: "Search…",
    customersSuggestionsDb: "Suggestions: customer no. and company names from the database",
    customersSuggestionsSaved: "Suggestions from saved customers",
    customersShow: "Show",
    customersAll: "all",
    customersMoreFilters: "More filters",
    customersLabelCustomerNr: "Customer no.",
    customersLabelCompany: "Company name",
    customersLabelContact: "Contact person",
    customersLabelPhone: "Phone",
    customersLabelZip: "ZIP",
    customersLabelCity: "City",
    customersLabelCountry: "Country",
    customersLabelSort: "Sort by",
    customersSortKundenNr: "Customer no.",
    customersSortFirmenname: "Company name",
    customersSortOrt: "City",
    customersSortPLZ: "ZIP",
    customersSortTermin: "Appointment",
    customersEmptyList:
      'No customers in the list. Clear filters ("all") or create a new customer.',
    customersSelectionCount: "Selection count:",
    customersLists: "Lists",
    customersClose: "Close",
    customersSave: "Save",
    customersFileTooBig:
      "File too large (max 2 MB in this demo until a server handles uploads).",
    customersFileReadError: "Could not read the file.",
    customersSaveFailed: "Save failed",
    customersThKuNr: "Cust. no.",
    customersThCompany: "Company",
    customersThAppointment: "Appointment",
    customersThIndustry: "Industry",
    customersThStreet: "Street",
    customersThZip: "ZIP",
    customersThCity: "City",
    customersThCountry: "Country",
    customersDrawerEntity: "Customer",
    customersLoading: "Loading…",
    customersDrawerNrLabel: "Customer no.",
    angeboteDeptHint: "Filters and list follow the classic OFFERS screen; layout like Customers.",
    verkaufterBestandSubtitle:
      "Sold inventory search — filters and columns aligned with the legacy system.",
    verkaufterBestandCount: "Number of selected vehicles:",
    abholauftraegeSubtitle:
      "Pickup list — VIN search and filters aligned with the legacy system.",
    abholauftraegeVinSearch: "Search chassis number",
    abholauftraegeCount: "Number of orders:",
    kennzeichenPageTitle: "License plate search",
    kennzeichenSearchHeader: "Search by license plate",
    kennzeichenSearchLabel: "Search license plate:",
    kennzeichenSearchButton: "Search",
    kennzeichenWildcardHint:
      "Use * as a wildcard for better matches. Example: DE*MA*101",
    kennzeichenColPosition: "Position no.",
    kennzeichenColKz: "Plate",
    kennzeichenColTable: "Table / source",
    kennzeichenNoHits: "No matches for this search.",
    kennzeichenEnterQuery: "Enter a plate or use * as placeholder.",
    kennzeichenHitCount: "Matches:",
    navDuplicateCustomers: "Duplicate customers",
    dupCustomersPageTitle: "Duplicate customers",
    dupCustomersFilterHint: "Filters apply immediately to the result list.",
    dupCustomersShow: "Show",
    dupCustomersAll: "all",
    dupCustomersKundenNr: "Customer no.:",
    dupCustomersFirma: "Company:",
    dupCustomersAnsprech: "Contact:",
    dupCustomersTel: "Phone:",
    dupCustomersFax: "Fax:",
    dupCustomersBranche: "Industry:",
    dupCustomersArt: "Type:",
    dupCustomersNotKii: "not KII/KEG/KSL",
    dupCustomersZpk: "ZPK:",
    dupCustomersMitVerkn: "Customer w/ links",
    dupCustomersNaAnz: "Show NA customers",
    dupCustomersNaHint: "Legacy field; filtering when data is connected.",
    dupCustomersAufnahmeVon: "Entry from",
    dupCustomersAufnahmeBis: "Entry until",
    dupCustomersSort: "Sort:",
    dupCustomersSortTel: "Phone",
    dupCustomersSortBez: "Relationship",
    dupCustomersThTel: "Phone",
    dupCustomersThT: "T",
    dupCustomersThZeichen: "Code",
    dupCustomersThArt: "Type",
    dupCustomersThMarkiert: "Marked",
    dupCustomersThBKNR: "Link cust. no.",
    dupCustomersThBFirma: "Link company",
    dupCustomersThBez: "Relationship",
    dupCustomersCount: "Count:",
    dupCustomersEmptyDb:
      "No duplicates found (or no matching customers in local storage). A fresh install includes demo customers with overlaps.",
    dupCustomersEmptyFilter: "No rows match these filters.",
    rechnungenPageTitle: "Invoices",
    rechnungenQuickSearch: "Company quick search:",
    rechnungenSuggestionsCompanies: "Saved company names",
    rechnungenSuggestionsKu: "Customer numbers",
    rechnungenShow: "Show",
    rechnungenAll: "all",
    rechnungenFilterHint: "Filters apply immediately to the list.",
    rechnungenNewInvoice: "Record new invoice",
    rechnungenLabelNr: "Invoice no.:",
    rechnungenLabelVonRDatum: "Invoice date from:",
    rechnungenLabelBisRDatum: "Invoice date to:",
    rechnungenLabelArt: "Type:",
    rechnungenLabelRechnungErst: "Invoice created by:",
    rechnungenLabelVerkaeufer: "Seller:",
    rechnungenLabelVermerk: "Note:",
    rechnungenLabelKundenNr: "Customer no.:",
    rechnungenLabelUstId: "VAT ID:",
    rechnungenLabelPositionsNr: "Position no.:",
    rechnungenLabelFgst: "Chassis no.:",
    rechnungenLabelVerkaufsNr: "Sales no.:",
    rechnungenFilterNichtErledigt: "Not completed",
    rechnungenFilterBhCheck: "BH check",
    rechnungenFilterNichtAbgeholt: "Not picked up",
    rechnungenSortRechnNr: "Invoice no.",
    rechnungenSortRDatum: "Invoice date",
    rechnungenSortBetrag: "Invoice amount",
    rechnungenThRechnNr: "Inv. no.",
    rechnungenThRDatum: "Inv. date",
    rechnungenThKundenNr: "Cust. no.",
    rechnungenThArt: "Type",
    rechnungenThBuchung: "Booking",
    rechnungenThBezahltAm: "Paid on",
    rechnungenThErsteller: "Created",
    rechnungenThVerkaeufer: "Seller",
    rechnungenThBetrag: "Amount",
    rechnungenCount: "Number of invoices:",
    rechnungenEmpty: "No matches. Reset filters with “all”.",
    rechnungenDrawerLabel: "Invoice",
    rechnungenDrawerNew: "(New)",
    rechnungenDrawerNewHint:
      "The full INVOICE form (line items, payment method, net/gross, print) will be added when the API is connected. For now you can filter the list and open demo invoices.",
    rechnungenCloseDrawer: "Close",
    headerChat: "Chat",
    chatTitle: "Chat",
    chatSearchPlaceholder: "Search or start a new chat",
    chatNewChat: "New chat",
    chatNewGroup: "New group",
    chatEmptyList: "No chats yet. Start a new one.",
    chatSelectThread: "Select a chat from the list.",
    chatBack: "Back",
    chatMembersCount: "{n} members",
    chatStatusOnline: "Online",
    chatStatusOffline: "Offline",
    chatPreviewPhoto: "📷 Photo",
    chatNoMessagesYet: "No messages yet",
    chatMessagePlaceholder: "Message",
    chatSend: "Send",
    chatAddPhoto: "Photo",
    chatAddFile: "File",
    chatNoContacts: "No other accounts. Register a second user in this browser.",
    chatGroupName: "Group name",
    chatGroupNamePh: "e.g. Project team",
    chatGroupMembers: "Members",
    chatCreateGroup: "Create group",
    chatGroupNeedMember: "Select at least one contact.",
    chatSendFailed: "Could not send message.",
    chatFileTooBig: "File too large (max 2 MB in this demo).",
    chatFileReadError: "Could not read file.",
    chatNotifBanner: "Enable desktop notifications for new messages?",
    chatNotifEnable: "Enable",
    chatNotifLater: "Later",
    chatNotifUnsupported: "This browser does not support notifications.",
    chatNotifDenied: "Notifications were denied.",
    chatNotifImage: "📷 Photo",
    chatNotifFile: "📎 File",
    chatSectionContacts: "Contacts",
    chatSectionChats: "Chats",
    chatStatusAway: "Away",
    chatYouBadge: "You",
    chatTickSent: "Sent",
    chatTickDelivered: "Delivered",
    chatTickRead: "Read",
  },
  fr: {
    navDashboard: "Tableau de bord",
    navSettings: "Paramètres",
    headerSearchPlaceholder: "Rechercher… n° client, entreprise (suggestions depuis la base)",
    headerSearchTitle: "Numéros clients et entreprises enregistrés",
    headerAddNew: "Ajouter",
    headerLogout: "Se déconnecter",
    sidebarSales: "Ventes",
    sidebarPurchase: "Achats",
    sidebarWorkshop: "Atelier",
    sidebarCarWash: "Station de lavage",
    sidebarHRM: "RH",
    navB2bPortal: "Portail B2B",
    commonCustomers: "Clients",
    commonInventory: "Stock",
    commonOffers: "Offres",
    commonInquiries: "Demandes",
    commonInvoices: "Factures",
    commonReports: "Rapports",
    commonCalendar: "Calendrier",
    commonUser: "Utilisateur",
    sidebarSoldInventory: "Stock vendu",
    sidebarPickupOrders: "Ordres d'enlèvement",
    sidebarPlateSearch: "Recherche plaque",
    sidebarCreditNotes: "Avoirs",
    sidebarPickupDeliveryCalendar: "Calendrier: enlèvement & livraison",
    sidebarWash: "Lavage",
    sidebarOrders: "Commandes",
    sidebarCashDesk: "Caisse",
    sidebarWorkshopCore: "Atelier · Cœur de métier",
    sidebarWorkshopStock: "Atelier · Stock & catalogues",
    sidebarWorkshopBilling: "Atelier · Facturation & caisse",
    sidebarWorkshopMore: "Atelier · Planification & plus",
    sidebarArticleIntake: "Réception marchandises",
    sidebarArticleCatalog: "Catalogue pièces",
    sidebarServiceCatalog: "Catalogue prestations",
    sidebarThirdPartyCatalog: "Prestations sous-traitées",
    sidebarInvoicesOpen: "Factures ouvertes",
    sidebarInvoicesPaid: "Factures payées",
    sidebarAccounting: "Comptabilité",
    sidebarSuppliers: "Fournisseurs",
    sidebarEmployees: "Employés",
    sidebarAttendance: "Présence",
    sidebarSalary: "Salaire",
    sidebarRolesPermissions: "Rôles & permissions",
    sidebarOnGroundTeam: "Équipe terrain",
    onGroundTeamTitle: "Terrain & équipe sur site",
    onGroundKpiActive: "Actifs sur site",
    onGroundKpiTransit: "En route",
    onGroundKpiStandby: "En astreinte",
    onGroundKpiShifts: "Équipes aujourd'hui",
    onGroundRosterTitle: "Équipe en mission",
    onGroundRoleDriver: "Chauffeur",
    onGroundRoleCoordinator: "Coordinatrice",
    onGroundRoleTech: "Technicien",
    onGroundStatusOnSite: "Sur site",
    onGroundStatusTransit: "Route",
    onGroundStatusStandby: "Astreinte",
    ogtStatusActive: "Actif",
    ogtStatusInProgress: "En cours",
    ogtStatusDone: "Terminé",
    ogtStatusPending: "En attente",
    ogtStatusBreak: "Pause",
    ogtStatusOffline: "Hors ligne",
    ogtSectionChecklists: "Check-lists",
    ogtChecklistTruck: "Check-list enlèvement camion",
    ogtChecklistTrailer: "Check-list remorque / semi-remorque",
    ogtChecklistTruckDigital: "Check-list numérique enlèvement camion",
    ogtChecklistTrailerDigital: "Check-list numérique remorque / semi-remorque",
    ogtFieldBrand: "Marque",
    ogtFieldType: "Type",
    ogtFieldBody: "Carrosserie",
    ogtFieldChassisNo: "N° de châssis",
    ogtFieldPnr: "N° P",
    ogtChecklistCheckpoint: "Point de contrôle",
    ogtCheckOk: "OK",
    ogtCheckNo: "Non",
    ogtChecklistRemarks: "Remarques",
    ogtTyresAxle1: "Pneus % essieu 1",
    ogtTyresAxle2: "Essieu 2",
    ogtTyresAxle3: "Essieu 3",
    ogtTyresAxle4: "Essieu 4",
    ogtSignature: "Signature",
    ogtEta: "ETA",
    ogtPriorityLow: "Faible",
    weekdayMon: "Lundi",
    weekdayTue: "Mardi",
    weekdayWed: "Mercredi",
    weekdayThu: "Jeudi",
    weekdayFri: "Vendredi",
    commonPrint: "Imprimer",
    commonDate: "Date",
    commonSales: "Vente",
    signatureDraw: "Dessiner",
    signatureType: "Saisir",
    signatureClear: "Effacer",
    signatureTypePlaceholder: "Saisissez le nom complet",
    settingsTitle: "Paramètres",
    settingsDisplay: "Affichage",
    settingsLanguage: "Langue",
    settingsLanguageHelp: "La langue sélectionnée est appliquée dans le tableau de bord.",
    settingsSystemAccount: "Système & compte",
    settingsAccount: "Compte",
    settingsNotifications: "Notifications",
    settingsSecurity: "Sécurité",
    settingsUpdatePassword: "Mettre à jour le mot de passe",
    settingsNotificationRules: "Règles de notification",
    settingsQuietHours: "Activer les heures calmes (22:00 - 07:00)",
    settingsLanguageRegion: "Langue & région",
    settingsLiveActivity: "Activité en direct",
    settingsNoActions: "Aucune action pour le moment",
    hrmTitle: "Gestion des ressources humaines",
    hrmSectionEmployees: "Employés",
    hrmSectionAttendance: "Présence",
    hrmSectionSalary: "Salaire",
    hrmSectionRoles: "Rôles & permissions",
    hrmColName: "Nom",
    hrmColRole: "Rôle",
    hrmColLocation: "Site",
    hrmColStatus: "Statut",
    hrmStatusActive: "Actif",
    hrmStatusOnboarding: "Intégration",
    hrmLabelNewHires: "Nouvelles embauches",
    hrmLabelAttrition: "Attrition",
    hrmLabelPresentToday: "Présents aujourd'hui",
    hrmLabelVacation: "Congés",
    hrmLabelSick: "Maladie",
    hrmLabelOpenShifts: "Postes ouverts",
    hrmLabelStatements: "Fiches de paie",
    hrmLabelSepaStatus: "Statut SEPA",
    hrmLabelValidationErrors: "Erreurs de validation",
    hrmLabelActiveRoles: "Rôles actifs",
    hrmLabelMfaActive: "MFA actif",
    hrmLabelPrivilegedUsers: "Utilisateurs privilégiés",
    hrmLabelClean: "Propre",
    dynamicAddWidget: "Ajouter un widget",
    dynamicResetLayout: "Réinitialiser la mise en page",
    dynamicHint: "Glissez les widgets vers une nouvelle position · Utilisez le coin pour redimensionner",
    dynamicDragToMove: "Glisser pour déplacer",
    dynamicMoveWidget: "Déplacer le widget",
    dynamicRemoveWidget: "Supprimer le widget",
    welcomeTitle: "Bienvenue dans le système de gestion DEMA",
    welcomeSubtitle: "Voici votre vue d'ensemble — Ventes, Achats et Lavage en un coup d'oeil.",
    quickActionsTitle: "Actions rapides",
    quickActionCustomer: "Créer un client",
    quickActionVehicle: "Enregistrer un véhicule",
    quickActionOffer: "Créer une offre",
    quickActionInvoice: "Créer une facture",
    tasksTitle: "Tâches & rappels",
    tasksHigh: "Élevée",
    tasksMedium: "Moyenne",
    tasksNew: "Nouveau",
    tasksItem1: "Offre pour le client Schmidt",
    tasksItem2: "Remise du véhicule demain 10:00",
    tasksItem3: "Vérifier la facture #2847",
    tasksItem4: "Confirmer le rendez-vous lavage",
    profileTime: "Heure",
    profileStatus: "Statut",
    profileActive: "Actif",
    profileInternalComms: "Communication interne active",
    profileRoleVerified: "Rôle vérifié",
    profileOpen: "Ouvrir le profil",
    salesTitle: "Performance des ventes",
    salesPeriod: "6 mois",
    salesRevenue: "Revenus",
    salesTotalRevenue: "Revenu total",
    salesClosedDeals: "Transactions conclues",
    salesProfit: "Bénéfice",
    inventoryTitle: "Vue du stock",
    inventoryVerfügbar: "Disponible",
    inventoryReserviert: "Réservé",
    inventoryVerkauft: "Vendu",
    financesTitle: "Finances ce mois",
    financeEinnahmen: "Entrées",
    financeAusgaben: "Dépenses",
    financeGewinn: "Bénéfice",
    financeIncome: "Entrées",
    financeExpenses: "Dépenses",
    financeProfit: "Bénéfice",
    calendarTitle: "Calendrier",
    appointmentsTitle: "Rendez-vous du jour",
    appointmentsNew: "Nouveau rendez-vous",
    widgetUnknown: "Widget inconnu",
    widgetGroupTables: "Tableaux",
    widgetGroupLists: "Listes",
    widgetGroupMedia: "Médias",
    widgetGroupCharts: "Graphiques",
    widgetGroupOverviews: "Aperçus",
    widgetGroupActions: "Actions",
    widgetGroupPlanning: "Planification",
    widgetGroupMisc: "Autres",
    widgetTitleWelcome: "Bienvenue",
    widgetTitleKpi: "KPI",
    widgetTitleTable: "Tableau",
    widgetTitleTodoList: "Liste de tâches",
    widgetTitlePicture: "Image",
    widgetTitleGraphLine: "Ligne",
    widgetTitleGraphBar: "Barres",
    widgetTitleGraphPie: "Secteurs",
    widgetTitleGraphArea: "Aires",
    widgetTitleSales: "Performance des ventes",
    widgetTitleInventory: "Vue du stock",
    widgetTitleQuickActions: "Actions rapides",
    widgetTitleTasks: "Tâches & rappels",
    widgetTitleFinances: "Finances",
    widgetTitleUserCard: "Module profil",
    widgetTitleProfile: "Module profil",
    widgetTitleCalendar: "Calendrier",
    widgetTitleAppointments: "Rendez-vous",
    widgetTitleMeetings: "Réunions",
    widgetTitleNotes: "Notes",
    loginSecureBadge: "Connexion sécurisée",
    loginTitle: "Se connecter",
    loginSubtitle:
      "Utilisez votre e-mail professionnel pour accéder au tableau de bord — ou essayez le compte démo.",
    loginDemoTitle: "Accès démo",
    loginEmail: "E-mail",
    loginPassword: "Mot de passe",
    loginPlaceholderEmail: "nom@entreprise.fr",
    loginShowPassword: "Afficher le mot de passe",
    loginHidePassword: "Masquer le mot de passe",
    loginSubmit: "Continuer vers le tableau de bord",
    loginNoAccount: "Pas encore de compte ?",
    loginRegister: "S'inscrire",
    loginB2bPortalLink: "Portail véhicules B2B (public)",
    signupBadge: "Nouveau compte",
    signupTitle: "Créer un compte",
    signupSubtitle:
      "Inscription au tableau de bord interne (démo : données uniquement dans ce navigateur).",
    signupPasswordMismatch: "Les mots de passe ne correspondent pas.",
    signupName: "Nom",
    signupPassword: "Mot de passe",
    signupConfirmPassword: "Confirmer le mot de passe",
    signupPlaceholderName: "Prénom et nom",
    signupPlaceholderPassword: "Au moins 6 caractères",
    signupPlaceholderConfirm: "Répéter le mot de passe",
    signupSubmit: "Créer le compte",
    signupHasAccount: "Déjà inscrit ?",
    signupLogin: "Se connecter",
    signupB2bLink: "Portail véhicules B2B (public)",
    customersTitle: "Clients",
    customersNewCustomer: "Nouveau client",
    customersArea: "Secteur",
    deptSales: "Ventes",
    deptPurchase: "Achats",
    deptWerkstatt: "Atelier",
    deptWaschanlage: "Station de lavage",
    customersDeptHint:
      "Un écran pour tous les secteurs : kunden ; option kunden_wash dans l'onglet lavage lors de l'édition.",
    customersQuickCompanySearch: "Recherche rapide entreprise :",
    customersSearchPlaceholder: "Rechercher…",
    customersSuggestionsDb: "Suggestions : n° client et entreprises depuis la base",
    customersSuggestionsSaved: "Suggestions depuis les clients enregistrés",
    customersShow: "Afficher",
    customersAll: "tout",
    customersMoreFilters: "Filtres avancés",
    customersLabelCustomerNr: "N° client",
    customersLabelCompany: "Entreprise",
    customersLabelContact: "Contact",
    customersLabelPhone: "Téléphone",
    customersLabelZip: "CP",
    customersLabelCity: "Ville",
    customersLabelCountry: "Pays",
    customersLabelSort: "Tri",
    customersSortKundenNr: "N° client",
    customersSortFirmenname: "Entreprise",
    customersSortOrt: "Ville",
    customersSortPLZ: "CP",
    customersSortTermin: "Rendez-vous",
    customersEmptyList:
      "Aucun client dans la liste. Réinitialisez les filtres (« tout ») ou créez un client.",
    customersSelectionCount: "Nombre sélectionné :",
    customersLists: "Listes",
    customersClose: "Fermer",
    customersSave: "Enregistrer",
    customersFileTooBig:
      "Fichier trop volumineux (max 2 Mo en démo tant qu'un serveur gère les fichiers).",
    customersFileReadError: "Impossible de lire le fichier.",
    customersSaveFailed: "Enregistrement échoué",
    customersThKuNr: "N° client",
    customersThCompany: "Entreprise",
    customersThAppointment: "Rendez-vous",
    customersThIndustry: "Secteur",
    customersThStreet: "Rue",
    customersThZip: "CP",
    customersThCity: "Ville",
    customersThCountry: "Pays",
    customersDrawerEntity: "Client",
    customersLoading: "Chargement…",
    customersDrawerNrLabel: "N° client",
    angeboteDeptHint:
      "Filtres et liste selon l'écran OFFRES classique; mise en page comme Clients.",
    commonSave: "Enregistrer",
    commonClose: "Fermer",
    commonApply: "Appliquer",
    commonName: "Nom",
    commonEmail: "E-mail",
    commonOn: "Activé",
    commonOff: "Désactivé",
    themeLight: "Clair",
    themeDark: "Sombre",
    themeSystem: "Système",
    settingsTimezone: "Fuseau horaire",
    settingsRoleProfile: "Profil de rôle",
    settingsRoleEmployee: "Employé",
    settingsRoleManager: "Manager",
    settingsNotifySalesAlerts: "Alertes ventes",
    settingsNotifyHrmApprovals: "Approbations RH",
    settingsNotifyPayrollErrors: "Erreurs de paie",
    settingsNotifyB2bLeads: "Leads B2B",
    settingsDateFormat: "Format de date",
    settingsActionChangePassword: "Changer le mot de passe",
    settingsActionManage2fa: "Gérer la 2FA",
    settingsActionReviewRoles: "Vérifier les rôles",
    settingsActionNotificationRules: "Règles de notification",
    settingsActionLanguageRegion: "Langue & région",
    settings2faStatus: "2FA",
    settingsLastPasswordChange: "Dernier changement de mot de passe",
    settingsNever: "Jamais",
    settingsRegion: "Région",
    settingsRegionGermany: "Allemagne",
    settingsRegionInternational: "International",
    settingsCurrentPassword: "Mot de passe actuel",
    settingsNewPassword: "Nouveau mot de passe",
    settingsConfirmPassword: "Confirmer le mot de passe",
    settingsHint2faToggled: "2FA basculée",
    settingsHintRoleUpdated: "Profil de rôle mis à jour",
    settingsHintFillPasswordFields: "Veuillez remplir tous les champs du mot de passe",
    settingsHintPasswordMinLength: "Le nouveau mot de passe doit contenir au moins 6 caractères",
    settingsHintPasswordsMismatch: "Les mots de passe ne correspondent pas",
    settingsHintPasswordUpdated: "Mot de passe mis à jour avec succès",
    settingsHintNotificationRulesSaved: "Règles de notification enregistrées",
    settingsHintRegionSaved: "Paramètres de région enregistrés",
    appRedirecting: "Redirection…",
  },
  es: {},
  it: {},
  pt: {},
  tr: {},
  ru: {},
  hi: {},
  ar: {},
  zh: {},
  ja: {},
};

const LANGUAGE_OVERRIDES: Record<Exclude<LanguageCode, "de" | "en" | "fr">, Record<string, string>> = {
  es: {
    navSettings: "Configuración",
    settingsTitle: "Configuración",
    settingsLanguage: "Idioma",
    navDashboard: "Panel",
  },
  it: {
    navSettings: "Impostazioni",
    settingsTitle: "Impostazioni",
    settingsLanguage: "Lingua",
    settingsLanguageHelp: "La lingua selezionata viene applicata a tutta la dashboard.",
    settingsSystemAccount: "Sistema e account",
    settingsAccount: "Account",
    settingsNotifications: "Notifiche",
    settingsDisplay: "Aspetto",
    settingsSecurity: "Sicurezza",
    settingsLiveActivity: "Attività in tempo reale",
    settingsNoActions: "Nessuna azione ancora",
    navDashboard: "Dashboard",
    headerSearchPlaceholder: "Cerca… N° cliente, ragione sociale (suggerimenti dal database)",
    headerSearchTitle: "Numeri cliente e ragioni sociali salvate",
    headerAddNew: "Aggiungi",
    headerLogout: "Esci",
    navB2bPortal: "Portale B2B",
    commonCustomers: "Clienti",
    commonInventory: "Magazzino",
    commonOffers: "Offerte",
    commonInquiries: "Richieste",
    commonInvoices: "Fatture",
    commonReports: "Report",
    commonCalendar: "Calendario",
    commonUser: "Utente",
    sidebarSoldInventory: "Magazzino venduto",
    sidebarPickupOrders: "Ordini di ritiro",
    sidebarPlateSearch: "Ricerca targa",
    sidebarCreditNotes: "Note di credito",
    sidebarPickupDeliveryCalendar: "Calendario: ritiro e consegna",
    sidebarWash: "Lavaggio",
    sidebarOrders: "Ordini",
    sidebarCashDesk: "Cassa",
    sidebarWorkshopCore: "Officina · Attività principali",
    sidebarWorkshopStock: "Officina · Magazzino e cataloghi",
    sidebarWorkshopBilling: "Officina · Fatture e cassa",
    sidebarWorkshopMore: "Officina · Pianificazione e altro",
    sidebarArticleIntake: "Entrata merci",
    sidebarArticleCatalog: "Catalogo ricambi",
    sidebarServiceCatalog: "Catalogo prestazioni",
    sidebarThirdPartyCatalog: "Prestazioni di terzi",
    sidebarInvoicesOpen: "Fatture aperte",
    sidebarInvoicesPaid: "Fatture pagate",
    sidebarAccounting: "Contabilità",
    sidebarSuppliers: "Fornitori",
    sidebarEmployees: "Dipendenti",
    sidebarAttendance: "Presenze",
    sidebarSalary: "Stipendio",
    sidebarRolesPermissions: "Ruoli e permessi",
    sidebarOnGroundTeam: "Team sul campo",
    onGroundTeamTitle: "Team sul campo e in sede",
    onGroundKpiActive: "Attivi in sede",
    onGroundKpiTransit: "In viaggio",
    onGroundKpiStandby: "In reperibilità",
    onGroundKpiShifts: "Turni oggi",
    onGroundRosterTitle: "Team in servizio",
    onGroundRoleDriver: "Autista",
    onGroundRoleCoordinator: "Coordinatrice",
    onGroundRoleTech: "Tecnico",
    onGroundStatusOnSite: "In sede",
    onGroundStatusTransit: "In viaggio",
    onGroundStatusStandby: "Reperibilità",
    sidebarSales: "Vendite",
    sidebarPurchase: "Acquisti",
    sidebarWorkshop: "Officina",
    sidebarCarWash: "Autolavaggio",
    sidebarHRM: "HR",
    dynamicAddWidget: "Aggiungi widget",
    dynamicResetLayout: "Ripristina layout",
    dynamicHint:
      "Trascina i widget · Usa l'angolo per ridimensionare (tranne i blocchi bloccati)",
    dynamicDragToMove: "Trascina per spostare",
    dynamicMoveWidget: "Sposta widget",
    dynamicRemoveWidget: "Rimuovi widget",
    welcomeTitle: "Benvenuto nel sistema di gestione DEMA",
    welcomeSubtitle: "La tua panoramica — Vendite, Acquisti e Autolavaggio a colpo d'occhio.",
    quickActionsTitle: "Azioni rapide",
    quickActionCustomer: "Crea cliente",
    quickActionVehicle: "Registra veicolo",
    quickActionOffer: "Crea offerta",
    quickActionInvoice: "Crea fattura",
    tasksTitle: "Attività e promemoria",
    tasksHigh: "Alta",
    tasksMedium: "Media",
    tasksNew: "Nuovo",
    profileTime: "Ora",
    profileStatus: "Stato",
    profileActive: "Attivo",
    profileOpen: "Apri profilo",
    salesTitle: "Performance vendite",
    salesPeriod: "6 mesi",
    salesRevenue: "Ricavi",
    salesTotalRevenue: "Ricavi totali",
    salesClosedDeals: "Contratti chiusi",
    salesProfit: "Utile",
    inventoryTitle: "Panoramica magazzino",
    financesTitle: "Finanze del mese",
    financeIncome: "Entrate",
    financeExpenses: "Uscite",
    financeProfit: "Utile",
    calendarTitle: "Calendario",
    appointmentsTitle: "Appuntamenti di oggi",
    appointmentsNew: "Nuovo appuntamento",
    widgetUnknown: "Widget sconosciuto",
    widgetGroupTables: "Tabelle",
    widgetGroupLists: "Elenchi",
    widgetGroupMedia: "Media",
    widgetGroupCharts: "Grafici",
    widgetGroupOverviews: "Panoramiche",
    widgetGroupActions: "Azioni",
    widgetGroupPlanning: "Pianificazione",
    widgetGroupMisc: "Altro",
    widgetTitleWelcome: "Benvenuto",
    widgetTitleKpi: "KPI",
    widgetTitleTable: "Tabella",
    widgetTitleTodoList: "Lista attività",
    widgetTitlePicture: "Immagine",
    widgetTitleGraphLine: "Linea",
    widgetTitleGraphBar: "Barre",
    widgetTitleGraphPie: "Torta",
    widgetTitleGraphArea: "Area",
    widgetTitleSales: "Performance vendite",
    widgetTitleInventory: "Panoramica magazzino",
    widgetTitleQuickActions: "Azioni rapide",
    widgetTitleTasks: "Attività e promemoria",
    widgetTitleFinances: "Finanze",
    widgetTitleUserCard: "Modulo profilo",
    widgetTitleProfile: "Modulo profilo",
    widgetTitleCalendar: "Calendario",
    widgetTitleAppointments: "Appuntamenti",
    widgetTitleMeetings: "Riunioni",
    widgetTitleNotes: "Note",
    loginSecureBadge: "Accesso sicuro",
    loginTitle: "Accedi",
    loginSubtitle:
      "Usa la tua email aziendale per entrare nella dashboard — o prova l'account demo.",
    loginDemoTitle: "Accesso demo",
    loginEmail: "Email",
    loginPassword: "Password",
    loginPlaceholderEmail: "nome@azienda.it",
    loginShowPassword: "Mostra password",
    loginHidePassword: "Nascondi password",
    loginSubmit: "Vai alla dashboard",
    loginNoAccount: "Non hai un account?",
    loginRegister: "Registrati",
    loginB2bPortalLink: "Portale veicoli B2B (pubblico)",
    signupBadge: "Nuovo account",
    signupTitle: "Crea account",
    signupSubtitle: "Registrazione alla dashboard interna (demo: dati solo in questo browser).",
    signupPasswordMismatch: "Le password non coincidono.",
    signupName: "Nome",
    signupPassword: "Password",
    signupConfirmPassword: "Conferma password",
    signupPlaceholderName: "Nome e cognome",
    signupPlaceholderPassword: "Almeno 6 caratteri",
    signupPlaceholderConfirm: "Ripeti password",
    signupSubmit: "Crea account",
    signupHasAccount: "Hai già un account?",
    signupLogin: "Accedi",
    signupB2bLink: "Portale veicoli B2B (pubblico)",
    customersTitle: "Clienti",
    customersNewCustomer: "Nuovo cliente",
    customersArea: "Area",
    deptSales: "Vendite",
    deptPurchase: "Acquisti",
    deptWerkstatt: "Officina",
    deptWaschanlage: "Autolavaggio",
    customersDeptHint:
      "Una maschera per tutte le aree: kunden; opzionale kunden_wash nella scheda Autolavaggio durante la modifica.",
    customersQuickCompanySearch: "Ricerca rapida azienda:",
    customersSearchPlaceholder: "Cerca…",
    customersSuggestionsDb: "Suggerimenti: n° cliente e ragioni sociali dal database",
    customersSuggestionsSaved: "Suggerimenti dai clienti salvati",
    customersShow: "Mostra",
    customersAll: "tutti",
    customersMoreFilters: "Altri filtri",
    customersLabelCustomerNr: "N° cliente",
    customersLabelCompany: "Ragione sociale",
    customersLabelContact: "Referente",
    customersLabelPhone: "Telefono",
    customersLabelZip: "CAP",
    customersLabelCity: "Città",
    customersLabelCountry: "Paese",
    customersLabelSort: "Ordina per",
    customersSortKundenNr: "N° cliente",
    customersSortFirmenname: "Ragione sociale",
    customersSortOrt: "Città",
    customersSortPLZ: "CAP",
    customersSortTermin: "Appuntamento",
    customersEmptyList:
      'Nessun cliente nell\'elenco. Azzera i filtri ("tutti") o crea un nuovo cliente.',
    customersSelectionCount: "N. selezionati:",
    customersLists: "Elenchi",
    customersClose: "Chiudi",
    customersSave: "Salva",
    customersFileTooBig: "File troppo grande (max 2 MB in questa demo).",
    customersFileReadError: "Impossibile leggere il file.",
    customersSaveFailed: "Salvataggio non riuscito",
    customersThKuNr: "N° cliente",
    customersThCompany: "Azienda",
    customersThAppointment: "Appuntamento",
    customersThIndustry: "Settore",
    customersThStreet: "Via",
    customersThZip: "CAP",
    customersThCity: "Città",
    customersThCountry: "Paese",
    customersDrawerEntity: "Cliente",
    customersLoading: "Caricamento…",
    customersDrawerNrLabel: "N° cliente",
    angeboteDeptHint:
      "Filtri ed elenco come la maschera classica OFFERTE; layout come Clienti.",
    appRedirecting: "Reindirizzamento…",
  },
  pt: {
    navSettings: "Configurações",
    settingsTitle: "Configurações",
    settingsLanguage: "Idioma",
    navDashboard: "Painel",
  },
  tr: {
    navSettings: "Ayarlar",
    settingsTitle: "Ayarlar",
    settingsLanguage: "Dil",
    navDashboard: "Gösterge Paneli",
  },
  ru: {
    navSettings: "Настройки",
    settingsTitle: "Настройки",
    settingsLanguage: "Язык",
    navDashboard: "Панель",
  },
  hi: {
    navSettings: "सेटिंग्स",
    settingsTitle: "सेटिंग्स",
    settingsLanguage: "भाषा",
    navDashboard: "डैशबोर्ड",
  },
  ar: {
    navSettings: "الإعدادات",
    settingsTitle: "الإعدادات",
    settingsLanguage: "اللغة",
    navDashboard: "لوحة التحكم",
  },
  zh: {
    navSettings: "设置",
    settingsTitle: "设置",
    settingsLanguage: "语言",
    navDashboard: "仪表板",
  },
  ja: {
    navSettings: "設定",
    settingsTitle: "設定",
    settingsLanguage: "言語",
    navDashboard: "ダッシュボード",
  },
};

for (const code of Object.keys(LANGUAGE_OVERRIDES) as Array<keyof typeof LANGUAGE_OVERRIDES>) {
  MESSAGES[code] = { ...MESSAGES.en, ...LANGUAGE_OVERRIDES[code] };
}

export type LanguageContextType = {
  language: LanguageCode;
  setLanguage: (language: LanguageCode) => void;
  t: (key: string, fallback?: string) => string;
  localeTag: string;
  languageOptions: LanguageOption[];
};

export const LanguageContext = createContext<LanguageContextType | null>(null);

function readLanguageFromAppSettings(): LanguageCode | null {
  try {
    const raw = localStorage.getItem(APP_SETTINGS_KEY);
    if (!raw) return null;
    const parsed = JSON.parse(raw) as { language?: string };
    const code = parsed.language;
    if (code && LANGUAGE_OPTIONS.some((l) => l.code === code)) return code as LanguageCode;
  } catch {
    // ignore
  }
  return null;
}

function getInitialLanguage(): LanguageCode {
  try {
    const stored = localStorage.getItem(STORAGE_KEY) as LanguageCode | null;
    if (stored && LANGUAGE_OPTIONS.some((l) => l.code === stored)) return stored;
    const fromSettings = readLanguageFromAppSettings();
    if (fromSettings) return fromSettings;
  } catch {
    // ignore
  }
  return "de";
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<LanguageCode>(getInitialLanguage);

  const setLanguage = useCallback((next: LanguageCode) => {
    try {
      localStorage.setItem(STORAGE_KEY, next);
    } catch {
      // ignore
    }
    setLanguageState(next);
  }, []);

  useEffect(() => {
    try {
      localStorage.setItem(STORAGE_KEY, language);
    } catch {
      // ignore
    }
    document.documentElement.lang = language;
  }, [language]);

  const value = useMemo<LanguageContextType>(
    () => ({
      language,
      setLanguage,
      t: (key, fallback = key) =>
        MESSAGES[language]?.[key] ?? MESSAGES.en[key] ?? fallback,
      localeTag: localeTagForLanguage(language),
      languageOptions: LANGUAGE_OPTIONS,
    }),
    [language, setLanguage]
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
}
